[2024-07-24T15:28:41.134+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:28:41.142+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.to_base scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-24T15:28:41.145+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.to_base scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-24T15:28:41.145+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T15:28:41.149+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): to_base> on 2024-07-15 00:00:00+00:00
[2024-07-24T15:28:41.151+0900] {standard_task_runner.py:64} INFO - Started process 96576 to run task
[2024-07-24T15:28:41.154+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'to_base', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp9ykzmmoh']
[2024-07-24T15:28:41.156+0900] {standard_task_runner.py:91} INFO - Job 345: Subtask to_base
[2024-07-24T15:28:41.171+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.to_base scheduled__2024-07-15T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:28:41.194+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='to_base' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-24T15:28:41.195+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:28:41.201+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:28:41.201+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                echo "base"\n                bash /Users/DE32/airflow/sh/tmp2base.sh 2024-07-15\n            ']
[2024-07-24T15:28:41.204+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:28:41.206+0900] {subprocess.py:93} INFO - base
[2024-07-24T15:28:41.209+0900] {subprocess.py:93} INFO - bash: /Users/DE32/airflow/sh/tmp2base.sh: No such file or directory
[2024-07-24T15:28:41.209+0900] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-24T15:28:41.209+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:28:41.212+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-24T15:28:41.214+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=import_db, task_id=to_base, run_id=scheduled__2024-07-15T00:00:00+00:00, execution_date=20240715T000000, start_date=20240724T062841, end_date=20240724T062841
[2024-07-24T15:28:41.217+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 345 for task to_base (Bash command failed. The command returned a non-zero exit code 127.; 96576)
[2024-07-24T15:28:41.260+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T15:28:41.267+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:28:41.267+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
