[2024-07-31T11:20:20.840+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T11:20:20.851+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-30T02:10:00+00:00 [queued]>
[2024-07-31T11:20:20.854+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-30T02:10:00+00:00 [queued]>
[2024-07-31T11:20:20.854+0900] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-31T11:20:20.861+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): throw.err> on 2024-07-30 02:10:00+00:00
[2024-07-31T11:20:20.863+0900] {standard_task_runner.py:64} INFO - Started process 10668 to run task
[2024-07-31T11:20:20.866+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'movie', 'throw.err', 'scheduled__2024-07-30T02:10:00+00:00', '--job-id', '727', '--raw', '--subdir', 'DAGS_FOLDER/movie.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpskf5fwlh']
[2024-07-31T11:20:20.868+0900] {standard_task_runner.py:91} INFO - Job 727: Subtask throw.err
[2024-07-31T11:20:20.882+0900] {task_command.py:426} INFO - Running <TaskInstance: movie.throw.err scheduled__2024-07-30T02:10:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-31T11:20:20.902+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie' AIRFLOW_CTX_TASK_ID='throw.err' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T02:10:00+00:00'
[2024-07-31T11:20:20.902+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T11:20:20.908+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-31T11:20:20.908+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-31T11:20:20.911+0900] {subprocess.py:86} INFO - Output:
[2024-07-31T11:20:20.913+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-31T11:20:20.913+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T11:20:20.916+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-31T11:20:20.917+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=movie, task_id=throw.err, run_id=scheduled__2024-07-30T02:10:00+00:00, execution_date=20240730T021000, start_date=20240731T022020, end_date=20240731T022020
[2024-07-31T11:20:20.921+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 727 for task throw.err (Bash command failed. The command returned a non-zero exit code 1.; 10668)
[2024-07-31T11:20:20.928+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T11:20:20.935+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T11:20:20.935+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-31T17:00:18.544+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T17:00:18.555+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-30T02:10:00+00:00 [queued]>
[2024-07-31T17:00:18.558+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie.throw.err scheduled__2024-07-30T02:10:00+00:00 [queued]>
[2024-07-31T17:00:18.558+0900] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-31T17:00:18.564+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): throw.err> on 2024-07-30 02:10:00+00:00
[2024-07-31T17:00:18.567+0900] {standard_task_runner.py:64} INFO - Started process 21017 to run task
[2024-07-31T17:00:18.569+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'movie', 'throw.err', 'scheduled__2024-07-30T02:10:00+00:00', '--job-id', '887', '--raw', '--subdir', 'DAGS_FOLDER/movie.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp4c43w2dy']
[2024-07-31T17:00:18.571+0900] {standard_task_runner.py:91} INFO - Job 887: Subtask throw.err
[2024-07-31T17:00:18.585+0900] {task_command.py:426} INFO - Running <TaskInstance: movie.throw.err scheduled__2024-07-30T02:10:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-31T17:00:18.606+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie' AIRFLOW_CTX_TASK_ID='throw.err' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T02:10:00+00:00'
[2024-07-31T17:00:18.606+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T17:00:18.612+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-31T17:00:18.612+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-31T17:00:18.615+0900] {subprocess.py:86} INFO - Output:
[2024-07-31T17:00:18.617+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-31T17:00:18.617+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T17:00:18.620+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-31T17:00:18.621+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=movie, task_id=throw.err, run_id=scheduled__2024-07-30T02:10:00+00:00, execution_date=20240730T021000, start_date=20240731T080018, end_date=20240731T080018
[2024-07-31T17:00:18.625+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 887 for task throw.err (Bash command failed. The command returned a non-zero exit code 1.; 21017)
[2024-07-31T17:00:18.635+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T17:00:18.642+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T17:00:18.642+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
