[2024-07-24T14:10:50.129+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T14:10:50.137+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T14:10:50.139+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T14:10:50.139+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T14:10:50.143+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): copy.log> on 2024-07-21 00:00:00+00:00
[2024-07-24T14:10:50.146+0900] {standard_task_runner.py:64} INFO - Started process 89760 to run task
[2024-07-24T14:10:50.148+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_bash', 'copy.log', 'scheduled__2024-07-21T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/simple_bash.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp7o_vntm6']
[2024-07-24T14:10:50.150+0900] {standard_task_runner.py:91} INFO - Job 48: Subtask copy.log
[2024-07-24T14:10:50.163+0900] {task_command.py:426} INFO - Running <TaskInstance: simple_bash.copy.log scheduled__2024-07-21T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T14:10:50.186+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_bash' AIRFLOW_CTX_TASK_ID='copy.log' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-21T00:00:00+00:00'
[2024-07-24T14:10:50.186+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T14:10:50.192+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T14:10:50.192+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            mkdir -p ~/data/20240721\n            cp ~/logs/history_20240721*.log ~/data/20240721/\n        ']
[2024-07-24T14:10:50.195+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T14:10:50.199+0900] {subprocess.py:93} INFO - cp: /Users/DE32/logs/history_20240721*.log: No such file or directory
[2024-07-24T14:10:50.199+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T14:10:50.200+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T14:10:50.202+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T14:10:50.204+0900] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_bash, task_id=copy.log, run_id=scheduled__2024-07-21T00:00:00+00:00, execution_date=20240721T000000, start_date=20240724T051050, end_date=20240724T051050
[2024-07-24T14:10:50.207+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task copy.log (Bash command failed. The command returned a non-zero exit code 1.; 89760)
[2024-07-24T14:10:50.210+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T14:10:50.218+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T14:10:50.218+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-24T14:22:56.582+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T14:22:56.589+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T14:22:56.591+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T14:22:56.591+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T14:22:56.595+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): copy.log> on 2024-07-21 00:00:00+00:00
[2024-07-24T14:22:56.598+0900] {standard_task_runner.py:64} INFO - Started process 91150 to run task
[2024-07-24T14:22:56.600+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_bash', 'copy.log', 'scheduled__2024-07-21T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/simple_bash.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp55x8rg8k']
[2024-07-24T14:22:56.602+0900] {standard_task_runner.py:91} INFO - Job 143: Subtask copy.log
[2024-07-24T14:22:56.615+0900] {task_command.py:426} INFO - Running <TaskInstance: simple_bash.copy.log scheduled__2024-07-21T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T14:22:56.637+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_bash' AIRFLOW_CTX_TASK_ID='copy.log' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-21T00:00:00+00:00'
[2024-07-24T14:22:56.637+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T14:22:56.644+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T14:22:56.644+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            mkdir -p ~/data/20240721\n            cp ~/logs/history_20240721*.log ~/data/20240721/\n        ']
[2024-07-24T14:22:56.647+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T14:22:56.651+0900] {subprocess.py:93} INFO - cp: /Users/DE32/logs/history_20240721*.log: No such file or directory
[2024-07-24T14:22:56.651+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T14:22:56.652+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T14:22:56.655+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T14:22:56.657+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=simple_bash, task_id=copy.log, run_id=scheduled__2024-07-21T00:00:00+00:00, execution_date=20240721T000000, start_date=20240724T052256, end_date=20240724T052256
[2024-07-24T14:22:56.661+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 143 for task copy.log (Bash command failed. The command returned a non-zero exit code 1.; 91150)
[2024-07-24T14:22:56.707+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T14:22:56.718+0900] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T14:22:56.720+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
