[2024-07-24T15:08:42.108+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:08:42.116+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.err_report scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T15:08:42.118+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.err_report scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T15:08:42.118+0900] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T15:08:42.122+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): err_report> on 2024-07-21 00:00:00+00:00
[2024-07-24T15:08:42.124+0900] {standard_task_runner.py:64} INFO - Started process 94796 to run task
[2024-07-24T15:08:42.127+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'err_report', 'scheduled__2024-07-21T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpqqqrwzzh']
[2024-07-24T15:08:42.128+0900] {standard_task_runner.py:91} INFO - Job 266: Subtask err_report
[2024-07-24T15:08:42.141+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.err_report scheduled__2024-07-21T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:08:42.162+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='err_report' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-21T00:00:00+00:00'
[2024-07-24T15:08:42.163+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:08:42.169+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:08:42.169+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo "err report"\n           ']
[2024-07-24T15:08:42.172+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:08:42.173+0900] {subprocess.py:93} INFO - err report
[2024-07-24T15:08:42.174+0900] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T15:08:42.174+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:08:42.179+0900] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_db, task_id=err_report, run_id=scheduled__2024-07-21T00:00:00+00:00, execution_date=20240721T000000, start_date=20240724T060842, end_date=20240724T060842
[2024-07-24T15:08:42.188+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T15:08:42.195+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:08:42.195+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
