[2024-07-24T15:09:49.433+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:09:49.443+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.to_tmp scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-07-24T15:09:49.446+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.to_tmp scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-07-24T15:09:49.446+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T15:09:49.451+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): to_tmp> on 2024-07-13 00:00:00+00:00
[2024-07-24T15:09:49.455+0900] {standard_task_runner.py:64} INFO - Started process 94879 to run task
[2024-07-24T15:09:49.457+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'to_tmp', 'scheduled__2024-07-13T00:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpz0pomucb']
[2024-07-24T15:09:49.459+0900] {standard_task_runner.py:91} INFO - Job 277: Subtask to_tmp
[2024-07-24T15:09:49.475+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.to_tmp scheduled__2024-07-13T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:09:49.499+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='to_tmp' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-13T00:00:00+00:00'
[2024-07-24T15:09:49.499+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:09:49.505+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:09:49.505+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                echo "tmp"\n                CSV_FILE=~/data/csv/20240713/csv.csv\n                echo $CSV_FILE\n                bash /Users/DE32/airflow/sh/to_tmp.sh $CSV_FILE {ds}\n            ']
[2024-07-24T15:09:49.508+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:09:49.510+0900] {subprocess.py:93} INFO - tmp
[2024-07-24T15:09:49.510+0900] {subprocess.py:93} INFO - /Users/DE32/data/csv/20240713/csv.csv
[2024-07-24T15:09:49.516+0900] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-07-24T15:09:49.520+0900] {subprocess.py:93} INFO - ERROR 1049 (42000): Unknown database 'cmd_history'
[2024-07-24T15:09:49.521+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T15:09:49.521+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:09:49.525+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T15:09:49.527+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=import_db, task_id=to_tmp, run_id=scheduled__2024-07-13T00:00:00+00:00, execution_date=20240713T000000, start_date=20240724T060949, end_date=20240724T060949
[2024-07-24T15:09:49.530+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 277 for task to_tmp (Bash command failed. The command returned a non-zero exit code 1.; 94879)
[2024-07-24T15:09:49.562+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T15:09:49.570+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:09:49.572+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
