[2024-07-24T15:12:29.762+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:12:29.771+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.to_tmp scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-24T15:12:29.775+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.to_tmp scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-24T15:12:29.775+0900] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T15:12:29.780+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): to_tmp> on 2024-07-15 00:00:00+00:00
[2024-07-24T15:12:29.784+0900] {standard_task_runner.py:64} INFO - Started process 95029 to run task
[2024-07-24T15:12:29.787+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'to_tmp', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp9hvx2ce9']
[2024-07-24T15:12:29.789+0900] {standard_task_runner.py:91} INFO - Job 290: Subtask to_tmp
[2024-07-24T15:12:29.806+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.to_tmp scheduled__2024-07-15T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:12:29.829+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='to_tmp' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-24T15:12:29.829+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:12:29.836+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:12:29.836+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                echo "tmp"\n                CSV_FILE=~/data/csv/20240715/csv.csv\n                echo $CSV_FILE\n                bash /Users/DE32/airflow/sh/to_tmp.sh $CSV_FILE {ds}\n            ']
[2024-07-24T15:12:29.839+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:12:29.840+0900] {subprocess.py:93} INFO - tmp
[2024-07-24T15:12:29.841+0900] {subprocess.py:93} INFO - /Users/DE32/data/csv/20240715/csv.csv
[2024-07-24T15:12:29.847+0900] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-07-24T15:12:29.851+0900] {subprocess.py:93} INFO - ERROR 1049 (42000): Unknown database 'cmd_history'
[2024-07-24T15:12:29.851+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T15:12:29.852+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:12:29.855+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T15:12:29.857+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=import_db, task_id=to_tmp, run_id=scheduled__2024-07-15T00:00:00+00:00, execution_date=20240715T000000, start_date=20240724T061229, end_date=20240724T061229
[2024-07-24T15:12:29.860+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 290 for task to_tmp (Bash command failed. The command returned a non-zero exit code 1.; 95029)
[2024-07-24T15:12:29.892+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T15:12:29.899+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:12:29.899+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
